#NEV_TEST> 100
### The external generator derives from GeneratorPythia8.
[GeneratorExternal]
fileName=${O2DPG_MC_CONFIG_ROOT}/MC/config/PWGHF/external/generator/generator_pythia8_embed_charmnuclei.C
funcName=GenerateHFEmbedCDeuteron(1., 10, -1., 1., 0, 0.4)

### includePartonEvent is needed to keep the c-deuteron in the event record, even if there are no partons in the event
[GeneratorPythia8]
config=${O2DPG_MC_CONFIG_ROOT}/MC/config/PWGHF/pythia8/generator/pythia8_cdeuteron_to_dkpi.cfg
includePartonEvent=true
