#!/bin/bash
COMMAND="GEN_TOPO_PARTITION=test DDMODE=processing GEN_TOPO_HASH=1 GEN_TOPO_SOURCE=v0.4 GEN_TOPO_LIBRARY_FILE=production/production.desc GEN_TOPO_WORKFLOW_NAME=synchronous-workflow WORKFLOW_DETECTORS=ALL WORKFLOW_DETECTORS_QC= WORKFLOW_DETECTORS_CALIB= WORKFLOW_PARAMETERS=EVENT_DISPLAY RECO_NUM_NODES_OVERRIDE= ./gen_topo.sh"
#COMMAND="GEN_TOPO_PARTITION=test DDMODE=processing GEN_TOPO_HASH=0 GEN_TOPO_SOURCE=$HOME/alice/O2DataProcessing GEN_TOPO_LIBRARY_FILE=production/production.desc GEN_TOPO_WORKFLOW_NAME=synchronous-workflow WORKFLOW_DETECTORS=ALL WORKFLOW_DETECTORS_QC= WORKFLOW_DETECTORS_CALIB= WORKFLOW_PARAMETERS=EVENT_DISPLAY RECO_NUM_NODES_OVERRIDE= ./gen_topo.sh"
echo Running $COMMAND 1>&2
eval $COMMAND
