#!/usr/bin/env python3
#
# Definition of common variables

REL_VAL_INTERPRETATION_GOOD = "GOOD"
REL_VAL_INTERPRETATION_WARNING = "WARNING"
REL_VAL_INTERPRETATION_NONCRIT_NC = "NONCRIT_NC"
REL_VAL_INTERPRETATION_CRIT_NC = "CRIT_NC"
REL_VAL_INTERPRETATION_UNKNOWN = "UNKNOWN"
REL_VAL_INTERPRETATION_BAD = "BAD"

REL_VAL_SEVERITIES = [REL_VAL_INTERPRETATION_GOOD, REL_VAL_INTERPRETATION_WARNING, REL_VAL_INTERPRETATION_NONCRIT_NC, REL_VAL_INTERPRETATION_CRIT_NC, REL_VAL_INTERPRETATION_BAD, REL_VAL_INTERPRETATION_UNKNOWN]
REL_VAL_SEVERITY_MAP = {v: i for i, v in enumerate(REL_VAL_SEVERITIES)}
REL_VAL_SEVERITY_COLOR_MAP = {REL_VAL_INTERPRETATION_GOOD: "green",
                              REL_VAL_INTERPRETATION_WARNING: "orange",
                              REL_VAL_INTERPRETATION_NONCRIT_NC: "cornflowerblue",
                              REL_VAL_INTERPRETATION_CRIT_NC: "navy",
                              REL_VAL_INTERPRETATION_BAD: "red",
                              REL_VAL_INTERPRETATION_UNKNOWN: "grey"}
