### The external generator derives from GeneratorPythia8.
[GeneratorExternal]
fileName=${O2DPG_ROOT}/MC/config/PWGGAJE/trigger/generator_pythia8_gaptrigger_jets.C
funcName=getGeneratorPythia8GapGenJE()
