---
name: Collect and print async labels

'on':
  pull_request:
    types:
      - opened
      - reopened
    branches:
      - master

permissions:
  pull-requests: write   # to update labels

jobs:
  clean:
    name: Collect and print async labels
    uses: alisw/ali-bot/.github/workflows/async-list-label.yml@master
    permissions:
      pull-requests: write   # to update labels
