name: Release

on:
  release:
    types: [published]
  
jobs:
  build_release:
    runs-on: ubuntu-18.04
    steps:
    - name: Install Kerberos
      run: |
        sudo apt-get update
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y krb5-user
        cat << \EOF > krb5.conf
        ${{secrets.KRB5CONF}}
        EOF
        grep rdns krb5.conf
        sudo mv -f krb5.conf /etc/krb5.conf
        
    - name: Trigger release in jenkins
      run: |
       echo ${{github.event.release.tag_name}} | grep -e 'prod-20[0-9][0-9][0-1][0-9]-[0-9][0-9][a-z]\?'
       echo ${{secrets.JENKINS_BOT_PASS}} | kinit ${{secrets.PRINCIPAL}}
       curl -X POST -k --negotiate -u : ${{secrets.API_URL}} -H 'Content-Type: application/x-www-form-urlencoded' -d 'O2DPG_TAG=${{github.event.release.tag_name}}'
       klist
       kdestroy
       
